Cargo.lock
src/lib.rs

I am hoping this will make rustdoc links to [jf_cap] and [reef]
work correctly.

Re-export crates which form part of this crate's interface.

---

Cargo.lock
Cargo.toml
src/hd.rs
src/lib.rs
src/loader.rs

bip39 depended on a fixed, outdated patch version of
unicode-normalization, which was incompatible with CAPE. bip0039
has no such problematic dependencies.

Use a better bip39 crate.

---

Cargo.lock
src/events.rs
src/lib.rs
src/testing/mocks.rs

This avoids the need to make a network call to get the tranasction
kind every time we receive a transaction.
See #70

Add transaction kind to Memos event.

---

Cargo.lock
Cargo.toml
src/asset_library.rs
src/bin/check_verified_asset_library.rs
src/bin/gen_signing_key.rs
src/bin/gen_verified_asset_library.rs
src/lib.rs
src/persistence.rs
src/testing/tests.rs

Extends Seahorse with the ability to
* create and sign files containing lists of assets
* verify and import these files in order to mark certain assets "verified"
The plan is to apply this to CAPE by
* generating a signing key pair specific to the CAPE wallet
* using the signing key (which should be kept a secret of Espresso Systems)
to sign a set of official CAPE assets
* distribute the signed CAPE asset library with the CAPE wallet
* adding code around CapeWallet creation to load and verify the CAPE asset library
Closes #30 
See EspressoSystems/cape-ui#37

Support verified assets

---

src/lib.rs
src/persistence.rs
src/testing/mocks.rs
src/testing/mod.rs
src/txn_builder.rs

* Built-in feature for burning outputs (in the general sense, not
the specific CAPE sense). Will be needed for #67.
* Fixes #13
For a while I thought I needed this for the CAPE wallet integration. Turns out it's not needed for that, but I think it's an improvement and we will want it eventually anyways.

Clean up handling of transaction outputs.

---

Cargo.lock
Cargo.toml
src/lib.rs
src/testing/mocks.rs
src/testing/tests.rs
src/txn_builder.rs

- Uses `UserAddress` rather than `UserPubKey` for freezing, to make freezing independent from `get_public_key`, i.e., user registeration.
- Modifies asset records type in the backend to use `UserAddress` as the lookup key, so that we don't need the encryption key to construct a `UserPubKey`.
Closes https://github.com/EspressoSystems/seahorse/issues/37.

Make freezing independent from get_public_key and modify backend records type

---

Cargo.lock
Cargo.toml
src/accounts.rs
src/key_scan.rs
src/lib.rs
src/persistence.rs
src/testing/mocks.rs
src/testing/mod.rs
src/testing/tests.rs

This makes it easy to provide a `scan_status` field of `AccountInfo`,
which clients can use to indicate when an account's balance may not
be up to date.

Move key scans into account data structures.

---

src/accounts.rs
src/testing/tests.rs

Replaces the `balance: u64` field of `AccountInfo` with `balances: HashMap<AssetCode, u64>`.
Closes https://github.com/EspressoSystems/seahorse/issues/103.

Replace AccountInfo field

---

src/loader.rs

This isn't a complete versioning solution, but it is at least an
escape hatch. If we ever need to push an update to a released product
that changes the format of persistent storage, the updated code can
check the first field of the wallet metadata and perform a migration
if it is out of date.
@bfish713 we should make sure this gets merged to whatever version
of Seahorse CAPE is using before people start using CAPE.

Add Seahorse version to wallet persistent storage.

---

src/key_scan.rs
src/lib.rs
src/txn_builder.rs

This should improve ledger scanner throughput as we scale to
larger block sizes.
Closes #137

Batch insert record commitments.

---

Cargo.lock
Cargo.toml

Pin everything to a released version before we release a Seahorse version.
Final step after this is to update CAPE to match these dependencies.

Pin All Dependencies to Tagged Versions

---

.github/workflows/bench.yml
.github/workflows/build.yml
Cargo.lock
Cargo.toml
src/asset_library.rs

This is a fix needed for CAPE, hence this PR. If all goes well I will port this to `main` in a separate PR.

Add alpha channel to stored icons

---

src/cli.rs
src/lib.rs
src/testing/bench.rs
src/testing/mod.rs
src/testing/tests.rs

- Replaces the receiver's `UserAddress` with `UserPubKey` for transfer and minting.
- Updates tests and CLI.
Closes https://github.com/EspressoSystems/seahorse/issues/118.

Replace UserAddress with UserPubKey for transfer and minting

---

src/events.rs
src/key_scan.rs
src/lib.rs
src/testing/mocks.rs

This will allow the CAPE wallet GUI to always display the transaction hash in the transaction history view. Currently, it displays "None" for received transactions.
If this is accepted, I will make the (small) change needed to support this in the EQS.

Include hash in transaction receive history

---

src/testing/tests.rs
src/txn_builder.rs

Prevent panic when allocating 0-amount fee records.

---

src/cli.rs
src/lib.rs
src/testing/bench.rs
src/testing/mocks.rs
src/testing/mod.rs
src/testing/tests.rs

This does a few things
- Removes KeyStream from backend
- No longer take a Keytree on backend initialization
- Update trivial loader for tests to take a key tree to make adding funded keys easier
- Update CLI test to add funded keys to the wallet where needed.  (Previously it relied on initializing the backend with the keytree with already funded keys)
Closes: https://github.com/EspressoSystems/seahorse/issues/189

Get `KeyTree` from storage and remove from backend

---

Cargo.lock
Cargo.toml
src/cli.rs
src/encryption.rs
src/hd.rs
src/loader.rs
src/loader/create.rs
src/loader/interactive.rs
src/loader/login.rs
src/loader/recovery.rs
src/loader/tests.rs
src/persistence.rs
src/secret.rs

Low priority on this review, it's not urgent, just something I've been wanting to do for a while.
The behavior of loading and creating keystores is a customization
point, with the KeystoreLoader trait defining the interface. This
is really nice, because it allows us to have different loaders with
different kinds of behavior. For example, we might have one loader
which only opens existing keystores, another which only creates new
ones, and another which knows how to recover a keystore from a
mnemonic phrase.
Unfortunately, over time we found ourselves with a single monolithic
loader, which was a tangle of different responsibilities. It included
an internal abstraction to handle both interactive input and preprogrammed
behavior with various combinations of a given mnemonic phrase and a …

Refactor loader implementations

---

src/persistence.rs

This is generally useful for inspecting metadata about a wallet (for example, version number, or mnemonic phrase). In particular, CAPE will use this by storing the contract address for which the wallet was created in the metadata, and then using the stored address to check if the wallet is up to date with the latest contract provided by the EQS.

Expose metadata from persistent storage

---

src/cli.rs
src/lib.rs
src/persistence.rs
src/testing/tests.rs

* Consider viewing and freezing accounts used if they are used to define an asset
* Do not require CLI implementations to use the default Loader or Metadata
* Expose metadata from persistent storage

Port improvements from release-0.2

---

Cargo.lock
Cargo.toml
src/key_scan.rs

When remembering a Merkle path during key scan, we need to make
sure to clear `leaf_to_forget` if `leaf_to_forget` is the remembered
leaf, otherwise we will just forget the path again as soon as more
commitments are appended.

Fix panic in key scan

---

Cargo.lock
Cargo.toml
src/key_scan.rs
src/lib.rs
src/persistence.rs
src/sparse_merkle_tree.rs
src/testing/mocks.rs
src/txn_builder.rs

Since MerkleTree from jf_primitives does not support pruning the
rightmost leaf, Seahorse uses a pattern of remembering if a leaf
should be forgotten while it is the rightmost, and then forgetting
it if necessary once a new leaf has been appended.
This pattern has some subtleties, and at least two critical bugs
have been found involving not properly updating the leaf-to-forget
state. Worse, this pattern is used by both TransactionState during
the usual ledger following and in key_scan during the retroactive
catch-up scan. Recently, a bug was found in key_scan that had been
fixed a long time ago in TransactionState.
This changes removes duplication by encapsulating the leaf-forgetting
pattern in a single type which can be used by both key_scan and
TransactionState. It also makes it …

Encapsulate sparse Merkle tree functionality in a type.

---

src/assets.rs

- Removes the `temporary` field from `Asset`.
- Skips `verified` when serializing.
- Adds verified set to `Assets`.
Closes https://github.com/EspressoSystems/seahorse/issues/196.

Improve the handling of verified assets in Asset Model

---

.github/workflows/build.yml
.github/workflows/slow-tests.yml
Cargo.toml
src/cli.rs
src/sparse_merkle_tree.rs
src/testing/mocks.rs

- Adds `feature = "slow-tests"` to slow tests.
- Moves slow tests from `Build` to a different workflow.
Closes https://github.com/EspressoSystems/espresso/issues/391.

Move slow tests to a separate workflow

---

src/lib.rs
src/persistence.rs
src/testing/mod.rs
src/testing/tests.rs

- Moves `AtomicStore` from `AtomicKeystoreStorage` to `KeystoreSession`.
- Commits store version in the upper level.
Closes https://github.com/EspressoSystems/seahorse/issues/203.

Move AtomicStore to upper level and refactor storage

---

src/lib.rs
src/transactions.rs
src/txn_builder.rs

This should be a model for a Transaction at any stage.  It should take over for the types we have now: `TransactionHistory`, `TransactionAwaitingMemos`, and `PendingTransaction`
Most of the information on a Transaction should never change.  I only added the editor interface for the parts that I think can change.  We can always add more setters to the editor later.
Closes: https://github.com/EspressoSystems/seahorse/issues/109

Transaction Model

---

src/assets.rs
src/key_value_store.rs
src/transactions.rs

Implements functions for persisting in-memory states of the Assets and Transactions models.
Closes https://github.com/EspressoSystems/seahorse/issues/225. Closes https://github.com/EspressoSystems/seahorse/issues/226.

Implement Persistable for in-memory states

---

src/key_value_store.rs
src/testing/bench.rs

* When creating wallets from a snapshotted state for benchmarking,
ensure the snapshotted state has no keys in it. Each benchmark
needs to carefully control which keys are in the wallet, so that
it can accurately measure viewer, receiver, and passive listener
wallets.
* Ensure wallets are dropped before the temp dirs containing their
storage. There are two ways to do this:
- When a (Keystore, ..., TempDir) tuple is dropped, the elements
are dropped in order, which is correct
- When a (Keystore, ..., TempDir) tuple is unpacked, as in
```
let (keystore, ..., _tmp_dir) = tuple;
```
then the local variables are dropped in _reverse_ order, which
is incorrect, so we need to explicitly `drop(keystore)` before
exiting the scope.
* Do not call commit_version and revert_version in KeyValueStore …

Fixes for benchmarks and related bugs

---

src/key_value_store.rs
src/lib.rs
src/records.rs
src/transactions.rs

Creating the Records Model to replace `RecordInfo` and `RecordsDatabase`
In order to do so I added a new persist able type which is a `HashMap` to `BTreeSet` multimap.  This is used to lookup records for a transaction where the amounts are ordered by value to avoid fragmentation.  I'm don't really like the name for the type `PersistableHashMapBTreeMultiMap` but not sure what's better.

Create Records Model

---

src/cli.rs
src/key_value_store.rs
src/lib.rs
src/records.rs
src/testing/tests.rs
src/transactions.rs

The transactions model would reload the in memory indexes from storage after every update to a transaction.  Since the index was changed to the persistable type with rollback, when we rebuild the index we enqueue an add change for every K,V pair in the index.  This means if we call revert we would end up removing every item from the index.  Obviously this is not intended.  This change fixes that by explicitly adding and removing only what changed in the index.  We only completely rebuild the index during create and immediately commit it so if the first storage transaction after creation fails we don't wipe the index.
Also this adds timestamps to `Record` and `Transaction` in the same pattern as the other models

Remove Transactions::reload() and add `created_time` and `modified_time` to record and transaction models

---

Cargo.lock
src/lib.rs
src/testing/mocks.rs

Unblocking myself to update espresso's seahorse dependency.  This is the simplest possible change which keeps everything working as it was previously.
There is still a change needed to make use of the returned Merkle Paths from `validate_and_apply` but that should not require changes in espresso after update seahorse.

Update Reef dependency

---

src/cli.rs

This was causing the slow tests to fail in the espresso repo.  I testing this in espresso by updating the Seahorse dependency to this branch and all the cli slow tests pass.

Fixing output of some CLI functions

---

src/lib.rs
src/testing/mocks.rs

Espresso needs this because nullifier proofs in the metastate API are indexed by block height, not nullifier set hash. This is the first of a (longer term) move towards indexing things primarily by state number/block height in general.

Allow backend access to block height when querying nullifiers

---

src/ledger_state.rs
src/lib.rs
src/meta.rs
src/state.rs
src/testing/mod.rs
src/testing/tests.rs

- Implements `KeystoreStores` to store all resources, which can be created by `create_stores`.
- Replaces resources in `KeystoreModel` with `KeystoreStores` and updates callers.
Closes https://github.com/EspressoSystems/seahorse/issues/227.

Implement `KeystoreStores` and refactor `KeystoreModel`

---

.github/workflows/bench.yml
.github/workflows/build.yml
.github/workflows/coverage.yml
.github/workflows/slow-tests.yml
src/cli.rs
src/io.rs
src/lib.rs
src/loader.rs
src/loader/create.rs
src/loader/interactive.rs
src/loader/login.rs
src/loader/recovery.rs
src/loader/tests.rs
src/meta.rs
src/reader.rs
src/state.rs
src/testing/cli_match.rs
src/testing/mod.rs

This should stop the tests with multiple clients from blocking all the executor threads, allowing us to run on just 1 or 2 cores (e.g. the GitHub runners).

Use `spawn_blocking` for blocking IO in CLI
