Cargo.lock
Cargo.toml
src/encryption.rs
src/hd.rs
src/lib.rs
src/loader.rs
src/persistence.rs
src/testing/mod.rs
src/testing/tests.rs

Switch to BIP39 mnemonics for checksum feature.

---

src/encryption.rs
src/loader.rs
src/persistence.rs

If the user has forgotten their password but still has their
encrypted files, they can generate a new password by inputting their
mnemonic.

Support recovery/password reset using mnemonic.

---

Cargo.lock
src/accounts.rs
src/cli.rs
src/lib.rs
src/persistence.rs
src/testing/mocks.rs
src/testing/mod.rs
src/testing/tests.rs

Depends on EspressoSystems/arbitrary-wrappers#15

Support accounts with metadata (description, used, etc.).

---

src/lib.rs
src/txn_builder.rs

Closes https://github.com/EspressoSystems/cape/issues/551.

Rename txn parameters to make src/dst more explicit

---

Cargo.lock
src/cli.rs
src/persistence.rs
src/testing/mocks.rs
src/testing/mod.rs

Depends on EspressoSystems/reef#29

Use CRS from ledger abstraction rather than creating directly

---

Cargo.lock
Cargo.toml
src/cli.rs
src/lib.rs
src/loader.rs
src/persistence.rs
src/testing/mocks.rs
src/txn_builder.rs

Because this ended up bumping into a versioning surprise in a test I was doing with persistence in espresso. :-/

Updating Snafu crate to 0.7

---

src/asset_library.rs
src/cli.rs
src/key_scan.rs

Preemptive, in anticipation of updating rust toolchain to 1.60.0 in the near future

pre-fix clippy issues for 1.60.0 toolchain

---

src/asset_library.rs
src/bin/gen_verified_asset_library.rs
src/lib.rs
src/persistence.rs
src/testing/tests.rs

If this PR is accepted, I will make PRs to update CAPE and Espresso.

More stylish default metadata for the native asset

---

src/txn_builder.rs

For non-native transfers, the previous implementation allocated the
fee record only from the set of accounts from which other input
records were actually used. This is needlessly restrictive; the fee
record ought to be able to come from any of the accounts listed as
available sending addresses.

Enable fee input to come from any of the sending accounts.

---

.github/workflows/bench.yml

@Ancient123 is this the right fix for [this failure](https://github.com/EspressoSystems/seahorse/runs/6065432253?check_suite_focus=true)?

Use Rust Docker for benchmarks CI

---

.github/workflows/bench.yml
.github/workflows/build.yml
Cargo.lock
Cargo.toml
src/asset_library.rs

Ported from release-0.2 branch

Support alpha channel in icons

---

Cargo.toml
src/key_scan.rs
src/testing/tests.rs
src/txn_builder.rs

Handle empty blocks correctly.

---

Cargo.lock
Cargo.toml
src/accounts.rs
src/cli.rs
src/lib.rs
src/testing/tests.rs
src/txn_builder.rs

Use big integers for aggregate amounts

---

src/cli.rs
src/lib.rs
src/testing/bench.rs
src/testing/tests.rs
src/txn_builder.rs

Make fee account optional for mint and freeze.

---

src/key_scan.rs
src/persistence.rs
src/testing/tests.rs
src/txn_builder.rs

Add change information to transaction history

---

src/testing/bench.rs

This should fix the failing build step where the benchmarks are failing I/O.

Don't ignore temp directory returned in benchmarks

---

Cargo.lock
Cargo.toml

In preparation for the upcoming CAPE release, let's make a new
release of Seahorse.

Release 0.2.4.

---

src/asset_library.rs
src/assets.rs
src/key_value_store.rs
src/lib.rs
src/persistence.rs

- Creates KeyValueStore for Seahorse models.
- Defines Asset, Assets and AssetEditor structs.
- Implements corresponding CRUD functions. 
Closes https://github.com/EspressoSystems/seahorse/issues/108, closes https://github.com/EspressoSystems/seahorse/issues/184.

Create KeyValueStore and Assets Model

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
src/persistence.rs

Update atomicstore to 0.1.3 so we can get atomic store log rotation in CAPE.

Release 0.2.6

---

Cargo.lock
Cargo.toml
src/persistence.rs

Ported from @sveitser 's change on release-0.2

Prune dynamic state snapshots

---

src/lib.rs

- Adds `assets_mut()` to `KeystoreModel`.
- Removed asset functions from `KeystoreModel` and replaced them with calls to `assets_mut`.
- Made asset functions on `Keystore` configurable only for tests.
Closes https://github.com/EspressoSystems/seahorse/issues/228.

Replace keystore functions with direct calls to assets

---

src/key_value_store.rs

Change the in-memory index of `KeyValueStore` to a persistable struct so that we can persist its changes.
Closes https://github.com/EspressoSystems/seahorse/issues/247.

Make the in-memory index of KV store persistable

---

src/testing/tests.rs

A ledger implementation may create some transactions during
initialization, and these transactions may end up in the history
of some of the wallets in a test network. Therefore, we need to
account for wallets' transaction history not being empty at the
start of `test_multixfr_keystore`.

Account for pre-existing txn history

---

Cargo.lock
Cargo.toml
src/encryption.rs

Combining and fixing conflicts in some Dependabot PRs

Update more dependencies
